Response to reviewer 2 comment 20
greenelab/meta-review pull request #171
Opened 2019-03-17 13:06 UTC by dhimmel

Response to reviewer 2 comment 20
Closes https://github.com/greenelab/meta-review/issues/149

2019-03-17 14:08 UTC, dhimmel commented
Ready for review

2019-03-18 11:55 UTC, agitter requested changes
These updates address the reviewer comments well, and I only have minor suggestions.

2019-03-18 11:55 UTC, agitter commented on content/02.main-text.md
> +Accordingly, manuscripts natively support javascript and can thus include any web-based interactive visualization.
Is JavaScript the formal capitalization?

Do we want to name any specific interactive visualization libraries here?  I'm not sure a reader will read `web-based interactive visualization` and think of graphics like what plotly, D3, Bokeh, etc. offer.

2019-03-18 11:55 UTC, agitter commented on content/response-to-reviewers.md
> +Regarding interactive notebooks, some projects (e.g. [_eLife_'s reproducible article](https://elifesciences.org/labs/ad58f08d/introducing-elife-s-first-computationally-reproducible-article)) are expl
We could add this citation to the existing Stencila citation we have.

Add apostrophe to `manuscript's`

2019-03-18 11:55 UTC, agitter commented on content/response-to-reviewers.md
> +One challenge of this approach is that most analysis require substantial code, scattered across many layers of dependencies and inputs.
`most analyses`

2019-03-18 11:55 UTC, agitter commented on content/response-to-reviewers.md
> +While we thought the dot plot was a valuable supplement, there was not strong support for switching from the ridgeline plot to the dot plot for the primary manuscript visualization.
I suggest following this sentence by one more that notes that our new Figure 2 caption alerts readers they can open the notebook in Binder to view the alternative visualizations or access the underlying data to make their own.

2019-03-19 15:14 UTC, dhimmel commented
@agitter take a look again, especially wrt reorganization in https://github.com/greenelab/meta-review/pull/171/commits/0c3f05612d74210db1781694af0fbf8a8e9adde0

2019-03-20 21:28 UTC, agitter approved these changes

2019-03-20 21:30 UTC, merged