Add revised workflow figures
greenelab/meta-review pull request #180
Opened 2019-03-25 20:52 UTC by cgreene

This adds the new workflow figures. I'll also update the legend.

2019-03-26 14:53 UTC, agitter requested changes
The caption text and figure look good.  Can you also please write a quick response to the reviewer describing why we kept the vertical orientation and what changes you made?  We've been linking the issue and pull request so that we don't have to copy all the text changes into the response letter.

2019-03-26 14:53 UTC, agitter commented on content/02.main-text.md
> +In this example, where manuscript text is shown in solid lines on the left of the timline and discussion on github is shown by squiggly lines to the right of the timeline, the contributor opens an is
```suggestion
In this example, where manuscript text is shown in solid lines on the left of the timeline and discussion on GitHub is shown by squiggly lines to the right of the timeline, the contributor opens an issue to discuss a manuscript modification.
```

2019-03-27 12:12 UTC, cgreene commented
@agitter response to reviewers updated and ready for another look! Thanks :)

2019-03-27 14:05 UTC, agitter approved these changes
Great!

2019-03-27 14:06 UTC, merged